dist: trusty

cache:
  directories:
    - ./path-to-your-frontend-folder/node_modules

before_script:
  - npm install --prefix path-to-your-frontend-folder

script:
  - npm run test --prefix path-to-your-frontend-folder